var tree = [["Icecave",,"",
                [["Flax","Icecave\/Flax.html","",
                [["Exception","Icecave\/Flax\/Exception.html","",
                [["AbstractHessianFaultException","Icecave\/Flax\/Exception\/AbstractHessianFaultException.html"," < Exception",
                [        ]],["DecodeException","Icecave\/Flax\/Exception\/DecodeException.html"," < Exception",
                [        ]],["EncodeException","Icecave\/Flax\/Exception\/EncodeException.html"," < Exception",
                [        ]],["NoSuchMethodException","Icecave\/Flax\/Exception\/NoSuchMethodException.html"," < AbstractHessianFaultException",
                [        ]],["NoSuchObjectException","Icecave\/Flax\/Exception\/NoSuchObjectException.html"," < AbstractHessianFaultException",
                [        ]],["ProtocolException","Icecave\/Flax\/Exception\/ProtocolException.html"," < AbstractHessianFaultException",
                [        ]],["RequireHeaderException","Icecave\/Flax\/Exception\/RequireHeaderException.html"," < AbstractHessianFaultException",
                [        ]],["ServiceException","Icecave\/Flax\/Exception\/ServiceException.html"," < AbstractHessianFaultException",
                [        ]]        ]],["Message","Icecave\/Flax\/Message.html","",
                [["Decoder","Icecave\/Flax\/Message\/Decoder.html","",
                [        ]],["DecoderState","Icecave\/Flax\/Message\/DecoderState.html"," < AbstractEnumeration",
                [        ]],["Encoder","Icecave\/Flax\/Message\/Encoder.html","",
                [        ]],["HessianConstants","Icecave\/Flax\/Message\/HessianConstants.html"," < AbstractEnumeration",
                [        ]]        ]],["Serialization","Icecave\/Flax\/Serialization.html","",
                [["Decoder","Icecave\/Flax\/Serialization\/Decoder.html","",
                [        ]],["DecoderState","Icecave\/Flax\/Serialization\/DecoderState.html"," < AbstractEnumeration",
                [        ]],["Encoder","Icecave\/Flax\/Serialization\/Encoder.html","",
                [        ]],["HessianConstants","Icecave\/Flax\/Serialization\/HessianConstants.html"," < AbstractEnumeration",
                [        ]],["Utility","Icecave\/Flax\/Serialization\/Utility.html","",
                [        ]]        ]],["Binary","Icecave\/Flax\/Binary.html","",
                [        ]],["HessianClient","Icecave\/Flax\/HessianClient.html","",
                [        ]],["HessianClientFactory","Icecave\/Flax\/HessianClientFactory.html","",
                [        ]],["HessianClientInterface","Icecave\/Flax\/HessianClientInterface.html","",
                [        ]],["Object","Icecave\/Flax\/Object.html","",
                [        ]],["PackageInfo","Icecave\/Flax\/PackageInfo.html","",
                [        ]]        ]]        ]]        ]

