var tree = [["Icecave",,"",
                [["Flax","Icecave\/Flax.html","",
                [["Serialization","Icecave\/Flax\/Serialization.html","",
                [["Exception","Icecave\/Flax\/Serialization\/Exception.html","",
                [["DecodeException","Icecave\/Flax\/Serialization\/Exception\/DecodeException.html"," < RuntimeException",
                [        ]]        ]],["Decoder","Icecave\/Flax\/Serialization\/Decoder.html","",
                [        ]],["DecoderState","Icecave\/Flax\/Serialization\/DecoderState.html"," < Enumeration",
                [        ]],["Encoder","Icecave\/Flax\/Serialization\/Encoder.html","",
                [        ]],["HessianConstants","Icecave\/Flax\/Serialization\/HessianConstants.html","",
                [        ]],["Utility","Icecave\/Flax\/Serialization\/Utility.html","",
                [        ]]        ]],["Wire","Icecave\/Flax\/Wire.html","",
                [["ProtocolDecoder","Icecave\/Flax\/Wire\/ProtocolDecoder.html","",
                [        ]],["ProtocolDecoderState","Icecave\/Flax\/Wire\/ProtocolDecoderState.html"," < Enumeration",
                [        ]],["ProtocolEncoder","Icecave\/Flax\/Wire\/ProtocolEncoder.html","",
                [        ]]        ]],["HessianClient","Icecave\/Flax\/HessianClient.html","",
                [        ]],["HessianClientFactory","Icecave\/Flax\/HessianClientFactory.html","",
                [        ]],["HessianClientInterface","Icecave\/Flax\/HessianClientInterface.html","",
                [        ]]        ]]        ]]        ]

